name: dream_journal
description: A Dream Journal apllication.

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.2
  characters: ^1.2.1
  sqflite: ^2.2.6
  path: ^1.8.2
  intl: ^0.18.0
  google_fonts: ^4.0.3
  flutter_sticky_header: ^0.6.5
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
